/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package positions;

import ibTradeApi.ibApi;
import ibTradeApi.ibApi.accountInfo;

/**
 *
 * @author earlie87
 */
public class accountInfoForm extends javax.swing.JFrame {
    String selectedAccount = null; 
    positions actPortfolio;
    
    ibApi actApi = ibApi.getActApi();
    ibApi.accountInfo actAccInfo = actApi.new accountInfo(selectedAccount);
  
    /**
     * Creates new form accountInfoForm
     */
    public accountInfoForm(positions posin) {
        double bp = 401230.12344;
        double cash = 100000.0;
    
        initComponents();
        actPortfolio = posin;
        if (true) {
            ManagedAccounts actManagedAcccounts = ManagedAccounts.getAllAccounts();
            for (int i = 0; i < actManagedAcccounts.numOf(); i++) {
            //selectAccountComboBox.addItem(actManagedAcccounts.getAnEnabledAccount(i));    

            }

            getAccountInfoButton.setEnabled(false);

            actApi.setActAccountInfo(actAccInfo);
        }
        focusAccountLable.setText(actPortfolio.getAccountNumber());
        actApi.setActAccountInfo(actAccInfo);
        getAccountInfoButton.setEnabled(true);
        actAccInfo.setAccount(actPortfolio.getAccountNumber());
        selectedAccount = actPortfolio.getAccountNumber();
        getAccountInfoButtonActionPerformed(null);
        
    }
    
    public void setActivePortfolio(positions posin) {
        actPortfolio = posin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        netLiqValueTextField = new javax.swing.JTextField();
        cashTextField = new javax.swing.JTextField();
        curAvailFundsTextField = new javax.swing.JTextField();
        curExessLiqtyTextField = new javax.swing.JTextField();
        specialMemAccountTextField = new javax.swing.JTextField();
        buyingPowerTextField = new javax.swing.JTextField();
        totalCashTextField = new javax.swing.JTextField();
        stockTextField = new javax.swing.JTextField();
        optionTextField = new javax.swing.JTextField();
        netLiqValTotalTextField = new javax.swing.JTextField();
        unrealizedPLTextField = new javax.swing.JTextField();
        reallizedPLTextField = new javax.swing.JTextField();
        getAccountInfoButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        focusAccountLable = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Display Account Information");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Balances");

        jLabel2.setText("Available For Trading");

        jLabel3.setText("Market Value");

        jLabel4.setText("NetLiqValue");

        jLabel5.setText("Cash");

        jLabel6.setText("CurAvailFunds");

        jLabel7.setText("CurExessLiqty");

        jLabel8.setText("SpecialMemAccount");

        jLabel9.setText("BuyingPower");

        jLabel10.setText("Total Cash");

        jLabel11.setText("Stock");

        jLabel12.setText("Option");

        jLabel13.setText("NetLiqValTotal");

        jLabel14.setText("UnrealizedP&L");

        jLabel15.setText("RealizedP&L");

        netLiqValueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netLiqValueTextFieldActionPerformed(evt);
            }
        });

        cashTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashTextFieldActionPerformed(evt);
            }
        });

        curAvailFundsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curAvailFundsTextFieldActionPerformed(evt);
            }
        });

        curExessLiqtyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curExessLiqtyTextFieldActionPerformed(evt);
            }
        });

        specialMemAccountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialMemAccountTextFieldActionPerformed(evt);
            }
        });

        buyingPowerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyingPowerTextFieldActionPerformed(evt);
            }
        });

        totalCashTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalCashTextFieldActionPerformed(evt);
            }
        });

        stockTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockTextFieldActionPerformed(evt);
            }
        });

        optionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionTextFieldActionPerformed(evt);
            }
        });

        netLiqValTotalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netLiqValTotalTextFieldActionPerformed(evt);
            }
        });

        unrealizedPLTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unrealizedPLTextFieldActionPerformed(evt);
            }
        });

        reallizedPLTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reallizedPLTextFieldActionPerformed(evt);
            }
        });

        getAccountInfoButton.setText("Update");
        getAccountInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAccountInfoButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jLabel17.setText("Account:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(23, 23, 23)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel3)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(jLabel6)
                                .add(jLabel2)
                                .add(jLabel7)
                                .add(jLabel4)
                                .add(jLabel5)
                                .add(jLabel8)
                                .add(jLabel9)
                                .add(jLabel10)
                                .add(jLabel11)
                                .add(jLabel12)
                                .add(jLabel13)
                                .add(jLabel14)
                                .add(jLabel15))
                            .add(jLabel1)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel17))
                        .add(34, 34, 34)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(getAccountInfoButton)
                                        .add(18, 18, 18)
                                        .add(closeButton))
                                    .add(stockTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 175, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(unrealizedPLTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 186, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(reallizedPLTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 186, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(0, 0, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(totalCashTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 179, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(optionTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 175, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(netLiqValTotalTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 186, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(curExessLiqtyTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 171, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                            .add(buyingPowerTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                            .add(specialMemAccountTextField))
                                        .add(curAvailFundsTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 171, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(cashTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 171, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(netLiqValueTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 171, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(focusAccountLable, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 192, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(187, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(focusAccountLable, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel17))
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(netLiqValueTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel4))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cashTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel5))
                        .add(18, 18, 18))
                    .add(layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(75, 75, 75)))
                .add(jLabel2)
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(curAvailFundsTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(curExessLiqtyTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(specialMemAccountTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(buyingPowerTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(24, 24, 24)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(totalCashTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(stockTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(optionTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(netLiqValTotalTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(unrealizedPLTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel15)
                    .add(reallizedPLTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(35, 35, 35)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(getAccountInfoButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(closeButton))
                .add(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void netLiqValueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netLiqValueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netLiqValueTextFieldActionPerformed

    private void curAvailFundsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curAvailFundsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curAvailFundsTextFieldActionPerformed

    private void totalCashTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalCashTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalCashTextFieldActionPerformed

    private void cashTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashTextFieldActionPerformed

    private void curExessLiqtyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curExessLiqtyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curExessLiqtyTextFieldActionPerformed

    private void specialMemAccountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialMemAccountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialMemAccountTextFieldActionPerformed

    private void buyingPowerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyingPowerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyingPowerTextFieldActionPerformed

    private void stockTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockTextFieldActionPerformed

    private void optionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionTextFieldActionPerformed

    private void netLiqValTotalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netLiqValTotalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netLiqValTotalTextFieldActionPerformed

    private void unrealizedPLTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unrealizedPLTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unrealizedPLTextFieldActionPerformed

    private void reallizedPLTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reallizedPLTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reallizedPLTextFieldActionPerformed

    private void getAccountInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAccountInfoButtonActionPerformed
        
        Object pressed = null;
        if (evt != null){
            pressed = evt.getActionCommand();
        }
        if (((pressed != null) && (pressed == "Update")) || (selectedAccount != null)) {
            actAccInfo.reqUpdateAccountInformation(true);
            myUtils.delay(2000);
            buyingPowerTextField.setText("123.3");
            buyingPowerTextField.setText(Double.toString(actAccInfo.getBuyingPowerVal()));
            cashTextField.setText(Double.toString(actAccInfo.getCashVal()));
            curAvailFundsTextField.setText(Double.toString(actAccInfo.getCurrentAvailFundsVal()));
            curExessLiqtyTextField.setText(Double.toString(actAccInfo.getCurrentExcessLiquidityVal()));
            reallizedPLTextField.setText(Double.toString(actAccInfo.getCurrentRealizedPandLVal()));
            unrealizedPLTextField.setText(Double.toString(actAccInfo.getCurrentUnrealizedPandLVal()));
            netLiqValueTextField.setText(Double.toString(actAccInfo.getNetLiqVal()));
            optionTextField.setText(Double.toString(actAccInfo.getOptionVal()));
            specialMemAccountTextField.setText(Double.toString(actAccInfo.getSpecialMemorandomAccountVal()));
            stockTextField.setText(Double.toString(actAccInfo.getStockVal()));
            totalCashTextField.setText(Double.toString(actAccInfo.getTotalCashVal()));    
            netLiqValTotalTextField.setText(Double.toString(actAccInfo.getNetLiqValueTotal()));
        }
        if(selectedAccount == null){
            commonGui.postInformationMsg("Select An Account.");
        }
    }//GEN-LAST:event_getAccountInfoButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("Account Info Form: window closing...");
        actAccInfo.reqUpdateAccountInformation(false);
        myUtils.delay(500);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        actAccInfo.reqUpdateAccountInformation(false);
        myUtils.delay(500);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buyingPowerTextField;
    private javax.swing.JTextField cashTextField;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField curAvailFundsTextField;
    private javax.swing.JTextField curExessLiqtyTextField;
    private javax.swing.JLabel focusAccountLable;
    private javax.swing.JButton getAccountInfoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField netLiqValTotalTextField;
    private javax.swing.JTextField netLiqValueTextField;
    private javax.swing.JTextField optionTextField;
    private javax.swing.JTextField reallizedPLTextField;
    private javax.swing.JTextField specialMemAccountTextField;
    private javax.swing.JTextField stockTextField;
    private javax.swing.JTextField totalCashTextField;
    private javax.swing.JTextField unrealizedPLTextField;
    // End of variables declaration//GEN-END:variables
}
