/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tradeMenus;

import positions.commonGui;

/**
 *
 * @author earlie87
 */
public class displayBullBearDialogForm extends javax.swing.JDialog {
    int userSelectedBullBearConditionInt = slopeDefs.oTURNED_OFF_INT;
    String userSelectedBullBearConditionStr = slopeDefs.oTURNED_OFF;
    //max is 53 because of the 200dma in one year of history.
    int userSelectedDaysOn = 0;
    boolean userSelectedGood = true;
    final int CONDITION_DAYS_MAX = 53;
    boolean enabled = false;
    /**
     * Creates new form displayBullBearDialogForm
     */
    public displayBullBearDialogForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public int getDaysOn(){
        return userSelectedDaysOn;
    }
    
    public String getBullBearConditionStr(){
        return userSelectedBullBearConditionStr;
    }
    public int getBullBearConditionInt(){
        return userSelectedBullBearConditionInt;
    }
    public boolean getUserSelectedGoodness(){
        return userSelectedGood;
    }
    public boolean getEnabled(){
        return enabled;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        daysOnTextField = new javax.swing.JTextField();
        bullBearConditionComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        finishedButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("BullBear Crossing");

        jLabel2.setText("ConditionPeriod");

        daysOnTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daysOnTextFieldActionPerformed(evt);
            }
        });

        bullBearConditionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TurnedOff", "BULL_50_200", "BULL_50_100_200", "BEAR_200_50", "BEAR_200_100_50" }));
        bullBearConditionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bullBearConditionComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("SelectCondition");

        finishedButton.setText("Done");
        finishedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishedButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(daysOnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bullBearConditionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finishedButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel4)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daysOnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bullBearConditionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishedButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daysOnTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daysOnTextFieldActionPerformed
        // TODO add your handling code here:
        userSelectedDaysOn = Integer.valueOf(daysOnTextField.getText());
        if (userSelectedDaysOn >= CONDITION_DAYS_MAX){
            
        }
    }//GEN-LAST:event_daysOnTextFieldActionPerformed

    private void bullBearConditionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bullBearConditionComboBoxActionPerformed
        // TODO add your handling code here:
        if (bullBearConditionComboBox.getItemCount() > 0) {
            userSelectedBullBearConditionStr = bullBearConditionComboBox.getSelectedItem().toString();
            userSelectedBullBearConditionInt = bullBearConditionComboBox.getSelectedIndex();
            enabled = !(userSelectedBullBearConditionStr.equals(slopeDefs.oTURNED_OFF));
        };
    }//GEN-LAST:event_bullBearConditionComboBoxActionPerformed

    private void finishedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishedButtonActionPerformed
        // TODO add your handling code here:
            boolean ok;
        
        userSelectedGood = (
                            ((userSelectedDaysOn < CONDITION_DAYS_MAX) && 
                            (!userSelectedBullBearConditionStr.equals(null))) ||
                            (!enabled)
                           );
        if (userSelectedGood == true) {           
            ok = ((commonGui.postConfirmationMsg(
                                            "You Entered: \n" +
                                            "ConditionPeriod: " + userSelectedDaysOn + "\n" +
                                            "Condition: " + userSelectedBullBearConditionStr
             ) == 0) || !enabled);            
        }else{
            ok = false;
        }
        
        if ((ok == true) && (userSelectedGood == true)){
            setVisible(false);
            dispose();   
        }else{
            if (userSelectedGood == false){
                commonGui.postInformationMsg("Check Input values and fix. Done aborted.");
            }else{
                commonGui.postInformationMsg("Done aborted.");
            }
        }
        
    }//GEN-LAST:event_finishedButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
            
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(displayBullBearDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(displayBullBearDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(displayBullBearDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(displayBullBearDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                displayBullBearDialogForm dialog = new displayBullBearDialogForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox bullBearConditionComboBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField daysOnTextField;
    private javax.swing.JButton finishedButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
