/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tradeMenus;

import ibTradeApi.ibApi;
import ibTradeApi.ibApi.historicalData;
import ibTradeApi.ibApi.quoteInfo;
import ibTradeApi.ibApi.historicalData.data;

import ibTradeApi.*;

/**
 *
 * @author earlie87
 */
public class displayQuoteDialogForm extends javax.swing.JDialog {

    private String tickerSymbol;
    private quoteInfo qInfo = new quoteInfo();
    private ibApi actIbApi = ibApi.getActApi();
    private boolean isOptionQuote = false;
    
    /**
     * Creates new form displayQuoteDialogForm
     */
    public displayQuoteDialogForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        optionSymbolCheckBox.setEnabled(true);
        addWindowListener(
                new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        setVisible(false);
                        dispose();
                    }
                });
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        displayStockQuotePanel = new javax.swing.JPanel();
        bidFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        askFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        lastFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        volumeFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        getQuoteButton = new javax.swing.JButton();
        enterTickerFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        optionSymbolCheckBox = new javax.swing.JCheckBox();
        closeButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Display Quote");

        displayStockQuotePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        displayStockQuotePanel.setName("displayStockQuotePanel");

        bidFormattedTextField.setEditable(false);
        bidFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidFormattedTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Bid");

        askFormattedTextField.setEditable(false);
        askFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                askFormattedTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Ask");

        lastFormattedTextField.setEditable(false);
        lastFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastFormattedTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Last");

        volumeFormattedTextField.setEditable(false);
        volumeFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeFormattedTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Volume");

        getQuoteButton.setText("Get Quote");
        getQuoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getQuoteButtonActionPerformed(evt);
            }
        });

        enterTickerFormattedTextField.setToolTipText("Enter Ticker Symbol\n");
        enterTickerFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterTickerFormattedTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Enter Ticker");

        optionSymbolCheckBox.setText("Option");
        optionSymbolCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionSymbolCheckBoxActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout displayStockQuotePanelLayout = new org.jdesktop.layout.GroupLayout(displayStockQuotePanel);
        displayStockQuotePanel.setLayout(displayStockQuotePanelLayout);
        displayStockQuotePanelLayout.setHorizontalGroup(
            displayStockQuotePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, displayStockQuotePanelLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .add(displayStockQuotePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, displayStockQuotePanelLayout.createSequentialGroup()
                        .add(displayStockQuotePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel6)
                            .add(jLabel7))
                        .add(29, 29, 29))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, displayStockQuotePanelLayout.createSequentialGroup()
                        .add(displayStockQuotePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel5))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(displayStockQuotePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(volumeFormattedTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, askFormattedTextField)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, lastFormattedTextField)
                    .add(enterTickerFormattedTextField)
                    .add(bidFormattedTextField))
                .add(67, 67, 67))
            .add(displayStockQuotePanelLayout.createSequentialGroup()
                .add(123, 123, 123)
                .add(displayStockQuotePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(closeButton)
                    .add(displayStockQuotePanelLayout.createSequentialGroup()
                        .add(getQuoteButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(optionSymbolCheckBox)))
                .addContainerGap())
        );
        displayStockQuotePanelLayout.setVerticalGroup(
            displayStockQuotePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(displayStockQuotePanelLayout.createSequentialGroup()
                .add(85, 85, 85)
                .add(displayStockQuotePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(lastFormattedTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(displayStockQuotePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bidFormattedTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(displayStockQuotePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(askFormattedTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(displayStockQuotePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(volumeFormattedTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .add(18, 18, 18)
                .add(displayStockQuotePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(enterTickerFormattedTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .add(24, 24, 24)
                .add(displayStockQuotePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(getQuoteButton)
                    .add(optionSymbolCheckBox))
                .add(35, 35, 35)
                .add(closeButton)
                .add(42, 42, 42))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(displayStockQuotePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(displayStockQuotePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bidFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bidFormattedTextFieldActionPerformed

    private void volumeFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volumeFormattedTextFieldActionPerformed

    private void lastFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastFormattedTextFieldActionPerformed

    private void askFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_askFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_askFormattedTextFieldActionPerformed

    private void enterTickerFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterTickerFormattedTextFieldActionPerformed
        
        tickerSymbol = enterTickerFormattedTextField.getText();
        
    }//GEN-LAST:event_enterTickerFormattedTextFieldActionPerformed

    private void getQuoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getQuoteButtonActionPerformed
        
        
        //actIbApi.getHistoricalData();
        qInfo = actIbApi.getQuote(tickerSymbol, isOptionQuote /*option?*/);
        //stockQuoteFormattedTextField.setText(Double.toString(qInfo.value));
        bidFormattedTextField.setText(Double.toString(qInfo.bid));
        askFormattedTextField.setText(Double.toString(qInfo.ask));
        volumeFormattedTextField.setText(Double.toString(qInfo.volume));
        lastFormattedTextField.setText(Double.toString(qInfo.last));
    }//GEN-LAST:event_getQuoteButtonActionPerformed

    private void optionSymbolCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionSymbolCheckBoxActionPerformed
        
        isOptionQuote = optionSymbolCheckBox.isSelected();
    }//GEN-LAST:event_optionSymbolCheckBoxActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(displayQuoteDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(displayQuoteDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(displayQuoteDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(displayQuoteDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                displayQuoteDialogForm dialog = new displayQuoteDialogForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField askFormattedTextField;
    private javax.swing.JFormattedTextField bidFormattedTextField;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel displayStockQuotePanel;
    private javax.swing.JFormattedTextField enterTickerFormattedTextField;
    private javax.swing.JButton getQuoteButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JFormattedTextField lastFormattedTextField;
    private javax.swing.JCheckBox optionSymbolCheckBox;
    private javax.swing.JFormattedTextField volumeFormattedTextField;
    // End of variables declaration//GEN-END:variables
}
