/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tradeMenus;

/**
 *
 * @author earlie87
 */
public class globalConfigDialogForm extends javax.swing.JDialog {

    /**
     * Creates new form globalConfigDialogForm
     */
    public globalConfigDialogForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fillerCheckBox = new javax.swing.JCheckBox();
        filler1CheckBox = new javax.swing.JCheckBox();
        oneTimeTradeCheckBox = new javax.swing.JCheckBox();
        stoplossGainLockCheckBox = new javax.swing.JCheckBox();
        autoTradeCheckBox = new javax.swing.JCheckBox();
        tradeLoopbackCheckBox = new javax.swing.JCheckBox();
        setdefaultsButton = new javax.swing.JButton();
        tradeDaysTextField = new javax.swing.JFormattedTextField();
        stockMoveTriggerTextField = new javax.swing.JFormattedTextField();
        pollFrequencyTextField = new javax.swing.JFormattedTextField();
        tradeTimeTextField = new javax.swing.JFormattedTextField();
        stockMoveOnetimeTriggerTextField = new javax.swing.JFormattedTextField();
        stopLossTriggerTextField = new javax.swing.JFormattedTextField();
        lockGainTriggerTextField = new javax.swing.JFormattedTextField();
        doneButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Global Configuration");

        fillerCheckBox.setText("Filler Enabled");
        fillerCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillerCheckBoxActionPerformed(evt);
            }
        });

        filler1CheckBox.setText("Filler 1 Enabled");
        filler1CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filler1CheckBoxActionPerformed(evt);
            }
        });

        oneTimeTradeCheckBox.setText("One-time trade Enabled");
        oneTimeTradeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneTimeTradeCheckBoxActionPerformed(evt);
            }
        });

        stoplossGainLockCheckBox.setText("StopLoss/GainLock Enable");
        stoplossGainLockCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stoplossGainLockCheckBoxActionPerformed(evt);
            }
        });

        autoTradeCheckBox.setText("Automatic Trade");
        autoTradeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoTradeCheckBoxActionPerformed(evt);
            }
        });

        tradeLoopbackCheckBox.setText("Trade Loopback Enable");
        tradeLoopbackCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tradeLoopbackCheckBoxActionPerformed(evt);
            }
        });

        setdefaultsButton.setText("Set Defaults");
        setdefaultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setdefaultsButtonActionPerformed(evt);
            }
        });

        tradeDaysTextField.setName("");
        tradeDaysTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tradeDaysTextFieldActionPerformed(evt);
            }
        });

        stockMoveTriggerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockMoveTriggerTextFieldActionPerformed(evt);
            }
        });

        pollFrequencyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pollFrequencyTextFieldActionPerformed(evt);
            }
        });

        tradeTimeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tradeTimeTextFieldActionPerformed(evt);
            }
        });

        stockMoveOnetimeTriggerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockMoveOnetimeTriggerTextFieldActionPerformed(evt);
            }
        });

        stopLossTriggerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopLossTriggerTextFieldActionPerformed(evt);
            }
        });

        lockGainTriggerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockGainTriggerTextFieldActionPerformed(evt);
            }
        });

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Number Of Trade Days");

        jLabel2.setText("Stock Move Trigger (%)");

        jLabel3.setText("Poll Frequency (seconds)");

        jLabel4.setText("Trade Time (format 12:45:PM)");

        jLabel5.setText("Stock Move One-time Trigger (%)");

        jLabel6.setText("StopLoss Trigger (%)");

        jLabel7.setText("LockGain Trigger (%)");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .add(8, 23, Short.MAX_VALUE)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(fillerCheckBox)
                                    .add(filler1CheckBox))
                                .add(26, 26, 26)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(stoplossGainLockCheckBox)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(tradeLoopbackCheckBox))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(oneTimeTradeCheckBox)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(autoTradeCheckBox))))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .add(21, 21, 21)
                                .add(tradeDaysTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(stockMoveTriggerTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(141, 141, 141)
                                .add(pollFrequencyTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(90, 90, 90))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(setdefaultsButton)
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(jLabel1)
                                                .add(28, 28, 28)
                                                .add(jLabel2)))
                                        .add(37, 37, 37)
                                        .add(jLabel3))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(15, 15, 15)
                                        .add(stopLossTriggerTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(101, 101, 101)
                                        .add(lockGainTriggerTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel4)
                            .add(tradeTimeTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 167, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel5)
                                .add(67, 67, 67))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(132, 132, 132)
                                .add(stockMoveOnetimeTriggerTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(doneButton)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel6)
                                .add(55, 55, 55)
                                .add(jLabel7)))
                        .add(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(fillerCheckBox)
                    .add(oneTimeTradeCheckBox)
                    .add(autoTradeCheckBox))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(filler1CheckBox)
                    .add(stoplossGainLockCheckBox)
                    .add(tradeLoopbackCheckBox))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(setdefaultsButton)
                .add(9, 9, 9)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel2)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(tradeDaysTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(pollFrequencyTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(stockMoveTriggerTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tradeTimeTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(stockMoveOnetimeTriggerTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(jLabel7))
                .add(4, 4, 4)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(stopLossTriggerTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lockGainTriggerTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(doneButton)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillerCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillerCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fillerCheckBoxActionPerformed

    private void oneTimeTradeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneTimeTradeCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneTimeTradeCheckBoxActionPerformed

    private void autoTradeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoTradeCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoTradeCheckBoxActionPerformed

    private void filler1CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filler1CheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filler1CheckBoxActionPerformed

    private void stoplossGainLockCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stoplossGainLockCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stoplossGainLockCheckBoxActionPerformed

    private void tradeLoopbackCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tradeLoopbackCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tradeLoopbackCheckBoxActionPerformed

    private void setdefaultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setdefaultsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setdefaultsButtonActionPerformed

    private void tradeDaysTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tradeDaysTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tradeDaysTextFieldActionPerformed

    private void stockMoveTriggerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockMoveTriggerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockMoveTriggerTextFieldActionPerformed

    private void pollFrequencyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pollFrequencyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pollFrequencyTextFieldActionPerformed

    private void tradeTimeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tradeTimeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tradeTimeTextFieldActionPerformed

    private void stockMoveOnetimeTriggerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockMoveOnetimeTriggerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockMoveOnetimeTriggerTextFieldActionPerformed

    private void stopLossTriggerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopLossTriggerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stopLossTriggerTextFieldActionPerformed

    private void lockGainTriggerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lockGainTriggerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lockGainTriggerTextFieldActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doneButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox autoTradeCheckBox;
    private javax.swing.JButton doneButton;
    private javax.swing.JCheckBox filler1CheckBox;
    private javax.swing.JCheckBox fillerCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField lockGainTriggerTextField;
    private javax.swing.JCheckBox oneTimeTradeCheckBox;
    private javax.swing.JFormattedTextField pollFrequencyTextField;
    private javax.swing.JButton setdefaultsButton;
    private javax.swing.JFormattedTextField stockMoveOnetimeTriggerTextField;
    private javax.swing.JFormattedTextField stockMoveTriggerTextField;
    private javax.swing.JFormattedTextField stopLossTriggerTextField;
    private javax.swing.JCheckBox stoplossGainLockCheckBox;
    private javax.swing.JFormattedTextField tradeDaysTextField;
    private javax.swing.JCheckBox tradeLoopbackCheckBox;
    private javax.swing.JFormattedTextField tradeTimeTextField;
    // End of variables declaration//GEN-END:variables
}
