/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tradeMenus;

import positions.commonGui;

/**
 *
 * @author earlie87
 */
public class MaWindowSizeDialogForm extends javax.swing.JDialog {

    /**
     * Creates new form MaWindowSizeDialogForm
     */
    public MaWindowSizeDialogForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    int userSelected50DayWindowSz = 0;
    int userSelected100DayWindowSz = 0;
    int userSelected200DayWindowSz = 0;
    boolean userSelectedGood = false;
    boolean userSelectedMaxValues = false;
    
    public int get50DayWindow(){
        return userSelected50DayWindowSz;
    }
    public int get100DayWindow(){
        return userSelected100DayWindowSz;
    }
    public int get200DayWindow(){
        return userSelected200DayWindowSz;
    }
    public boolean allGood(){
        return userSelectedGood;
    }
    public void set50DayWindow(int sz){
        userSelected50DayWindowSz = sz;
        sz50DayTextField.setText(Integer.toString(sz));
    }
    public void set100DayWindow(int sz){
        userSelected100DayWindowSz = sz;
        sz100DayTextField.setText(Integer.toString(sz));
    }
    public void set200DayWindow(int sz){
        userSelected200DayWindowSz = sz;
        sz200DayTextField.setText(Integer.toString(sz));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sz50DayTextField = new javax.swing.JTextField();
        sz100DayTextField = new javax.swing.JTextField();
        sz200DayTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        finishButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        setMaxValuesCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Moving Average Window Size");

        jLabel2.setText("50Day:");

        jLabel3.setText("100Day:");

        jLabel4.setText("200Day:");

        sz50DayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sz50DayTextFieldActionPerformed(evt);
            }
        });

        sz100DayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sz100DayTextFieldActionPerformed(evt);
            }
        });

        sz200DayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sz200DayTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Max202");

        jLabel6.setText("Max152");

        jLabel7.setText("Max52");

        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        setMaxValuesCheckBox.setText("SetMaxValues");
        setMaxValuesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMaxValuesCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sz200DayTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(sz50DayTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                            .addComponent(sz100DayTextField))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelButton)
                                .addGap(47, 47, 47)
                                .addComponent(finishButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(setMaxValuesCheckBox)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sz50DayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sz100DayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sz200DayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(setMaxValuesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(finishButton))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sz200DayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sz200DayTextFieldActionPerformed
        // TODO add your handling code here:
        userSelected200DayWindowSz = Integer.valueOf(sz200DayTextField.getText());
        if (userSelected200DayWindowSz >= slopeDefs.MA_200DAY_MAXSZ){
            
        }
    }//GEN-LAST:event_sz200DayTextFieldActionPerformed

    private void sz50DayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sz50DayTextFieldActionPerformed
        // TODO add your handling code here:
        userSelected50DayWindowSz = Integer.valueOf(sz50DayTextField.getText());
        if (userSelected50DayWindowSz >= slopeDefs.MA_50DAY_MAXSZ){
            
        }
    }//GEN-LAST:event_sz50DayTextFieldActionPerformed

    private void sz100DayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sz100DayTextFieldActionPerformed
        // TODO add your handling code here:
        userSelected100DayWindowSz = Integer.valueOf(sz100DayTextField.getText());
        if (userSelected100DayWindowSz >= slopeDefs.MA_100DAY_MAXSZ){
            
        }
    }//GEN-LAST:event_sz100DayTextFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        // TODO add your handling code here:
              boolean ok;
        userSelectedGood = (
                            (userSelected50DayWindowSz <= slopeDefs.MA_50DAY_MAXSZ) && 
                            (userSelected100DayWindowSz <= slopeDefs.MA_100DAY_MAXSZ) &&
                            (userSelected200DayWindowSz <= slopeDefs.MA_200DAY_MAXSZ)
                           );
        if (userSelectedGood == true){
            ok = (commonGui.postConfirmationMsg(
                                            "You Entered: \n" +
                                            "50Day: " + userSelected50DayWindowSz + "\n" +
                                            "100Day: " + userSelected100DayWindowSz + "\n" +
                                            "200Day: " + userSelected200DayWindowSz
             ) == 0);            
        }else{
            ok = false;
        }
        
        if ((ok == true) && (userSelectedGood == true)){
            setVisible(false);
            dispose();   
        }else{
            if (userSelectedGood == false){
                commonGui.postInformationMsg("Check Input values and fix. Done aborted.");
            }else{
                commonGui.postInformationMsg("Done aborted.");
            }
        }      
    }//GEN-LAST:event_finishButtonActionPerformed

    private void setMaxValuesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMaxValuesCheckBoxActionPerformed
        // TODO add your handling code here:
        
        userSelectedMaxValues = setMaxValuesCheckBox.isEnabled();       
        setMaxValuesCheckBox.setEnabled(userSelectedMaxValues);
        if(userSelectedMaxValues == true){
            set50DayWindow(slopeDefs.MA_50DAY_MAXSZ);
            set100DayWindow(slopeDefs.MA_100DAY_MAXSZ);
            set200DayWindow(slopeDefs.MA_200DAY_MAXSZ);
        }
        
    }//GEN-LAST:event_setMaxValuesCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaWindowSizeDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaWindowSizeDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaWindowSizeDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaWindowSizeDialogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MaWindowSizeDialogForm dialog = new MaWindowSizeDialogForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton finishButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JCheckBox setMaxValuesCheckBox;
    private javax.swing.JTextField sz100DayTextField;
    private javax.swing.JTextField sz200DayTextField;
    private javax.swing.JTextField sz50DayTextField;
    // End of variables declaration//GEN-END:variables
}
