/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tradeMenus;

import java.io.File;
import java.text.DecimalFormat;
import positions.myUtils;

/**
 *
 * @author earlie87
 */
public class PurchaseLimitDialog extends javax.swing.JDialog {	
	PurchaseLimits purchaseLimits = new PurchaseLimits(100000, 20000, 100, false);
	boolean limitsSaved = false;
    final String PL_FILE_NAME = "purchaseLimits.ser";
    String purchaseLimitsFileName = "";
	/**
	 * Creates new form PurchaseLimitDialog
	 */
	public PurchaseLimitDialog(java.awt.Frame parent, boolean modal, double accLimitIn, double posLimitIn, int byStocklimitIn, boolean divideEquallyAmongAll) {
		super(parent, modal);
		initComponents();
		File f = null; 
		purchaseLimitsFileName = myUtils.getMyWorkingDirectory() + "/src/supportFiles/" + PL_FILE_NAME;
        f = new File(purchaseLimitsFileName);
        if(f.exists()){
            purchaseLimits = purchaseLimits.deSerialize(purchaseLimitsFileName);
        }else{
            purchaseLimits.setAccountLimit(accLimitIn);
            purchaseLimits.setPositionDollarAmountLimit(posLimitIn);  
			purchaseLimits.setPositionFixedNumOfSharesLimit(byStocklimitIn);
			purchaseLimits.setDivideEqallyAmongAll(divideEquallyAmongAll);
        }               
        
		accountPurchaseLimitTextField.setText(purchaseLimits.displayIt(purchaseLimits.getAccountLimit()));
        limitPerStockDollarTextField.setText(purchaseLimits.displayIt(purchaseLimits.getPositionDollarAmountLimit()));
		limitPerStockNumOfSharesTextField.setText(Integer.toString(purchaseLimits.getPositionFixedNumOfSharesLimit()));
		equallyDividedRadioButton.setSelected(purchaseLimits.getDivideEquallAmongAll());
	}
	public PurchaseLimits getPurchaseLimits(){
        return purchaseLimits;
    }
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        accountPurchaseLimitTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        limitPerStockDollarTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        limitPerStockNumOfSharesTextField = new javax.swing.JTextField();
        doneButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        equallyDividedRadioButton = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Purchase Limits"));

        jLabel1.setText("Per Account:");

        accountPurchaseLimitTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountPurchaseLimitTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Per Stock:");

        limitPerStockDollarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limitPerStockDollarTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Fixed Dollar Amt:");

        jLabel4.setText("Fixed Number Of Shares:");

        limitPerStockNumOfSharesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limitPerStockNumOfSharesTextFieldActionPerformed(evt);
            }
        });

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Or");

        jLabel6.setText("Equally Divided Among Stocks:");

        equallyDividedRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equallyDividedRadioButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Or");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accountPurchaseLimitTextField)))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(84, 84, 84))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(155, 155, 155)
                                .addComponent(equallyDividedRadioButton))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(limitPerStockNumOfSharesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(limitPerStockDollarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(doneButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(accountPurchaseLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limitPerStockDollarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(limitPerStockNumOfSharesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(equallyDividedRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(doneButton)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountPurchaseLimitTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountPurchaseLimitTextFieldActionPerformed
        // TODO add your handling code here:
		purchaseLimits.setAccountLimit(Double.parseDouble(accountPurchaseLimitTextField.getText()));
		accountPurchaseLimitTextField.setText(purchaseLimits.displayIt(purchaseLimits.getAccountLimit()));
		System.out.println("\ntotalAccountPurchaseLimit: " + purchaseLimits.getAccountLimit());
    }//GEN-LAST:event_accountPurchaseLimitTextFieldActionPerformed

    private void limitPerStockDollarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitPerStockDollarTextFieldActionPerformed
        // TODO add your handling code here:
		purchaseLimits.setPositionDollarAmountLimit(Double.parseDouble(limitPerStockDollarTextField.getText()));
		limitPerStockDollarTextField.setText(purchaseLimits.displayIt(purchaseLimits.getPositionDollarAmountLimit()));
		System.out.println("\n:limitPerStockDollarAmmount " + purchaseLimits.getPositionDollarAmountLimit());
    }//GEN-LAST:event_limitPerStockDollarTextFieldActionPerformed

    private void limitPerStockNumOfSharesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitPerStockNumOfSharesTextFieldActionPerformed
        // TODO add your handling code here:
		purchaseLimits.setPositionFixedNumOfSharesLimit(Integer.parseInt(limitPerStockNumOfSharesTextField.getText()));
		limitPerStockNumOfSharesTextField.setText(Double.toString(purchaseLimits.getPositionFixedNumOfSharesLimit()));
		System.out.println("\nlimitByNumOfShares: " + purchaseLimits.getPositionFixedNumOfSharesLimit());
    }//GEN-LAST:event_limitPerStockNumOfSharesTextFieldActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
		purchaseLimits.serialize(purchaseLimits, purchaseLimitsFileName);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_doneButtonActionPerformed

    private void equallyDividedRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equallyDividedRadioButtonActionPerformed
        // TODO add your handling code here:
		purchaseLimits.setDivideEqallyAmongAll(equallyDividedRadioButton.isSelected());
		System.out.println("\nsetDivideEquallyAmontAll: " + purchaseLimits.getDivideEquallAmongAll());
    }//GEN-LAST:event_equallyDividedRadioButtonActionPerformed
	public double getTotalAccPurchaseLimit(){
		return purchaseLimits.getAccountLimit();
	}
	public double getLimitPerStockDollarAmount(){
		return purchaseLimits.getPositionDollarAmountLimit();
	}
	public double getLimitByNumOfShares(){
		return purchaseLimits.getPositionFixedNumOfSharesLimit();
	}
	public boolean getDivideEquallyAmongAll(){
		return purchaseLimits.getDivideEquallAmongAll();
	}
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PurchaseLimitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PurchaseLimitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PurchaseLimitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PurchaseLimitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				PurchaseLimitDialog dialog = new PurchaseLimitDialog(new javax.swing.JFrame(), true, 0.0, 0.0, 0, false);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountPurchaseLimitTextField;
    private javax.swing.JButton doneButton;
    private javax.swing.JCheckBox equallyDividedRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField limitPerStockDollarTextField;
    private javax.swing.JTextField limitPerStockNumOfSharesTextField;
    // End of variables declaration//GEN-END:variables
}
