/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tradeMenus;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import positions.commonGui;
import positions.*;


/**
 *
 * @author earlie87
 */
public class setRunPositionsTraderDialogForm extends javax.swing.JDialog {

    positions actPositions = null;
    boolean readyToRun = false;
    boolean runTrader = false;
    positionStatistics actStats = null;
    private positionTrader actTrader = null;
    private positionChart actChart = null;
    private tradeHandler actTradeHandler = null;
    private alarmsEvents actAlarmsEvents = null;
 
    
    private String tickList[];
    private String selectedTicker;
    /**
     * Creates new form setRunPositionsTraderDialogForm
     */
    public setRunPositionsTraderDialogForm(java.awt.Frame parent, boolean modal, positions allpos) {
        
        super(parent, modal);
        initComponents();
        
        addWindowListener(
                new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        setVisible(false);
                        dispose();
                    }
                });
        actPositions = allpos;
        int ix = 0;
        tickList = myUtils.fillTickerList(actPositions);
        for ( ix = 0; ix < tickList.length; ix++) {
            tickerComboBox.addItem(tickList[ix]);
        }
        if (ix > 0) {
            tickerComboBox.setSelectedItem(tickList[0]);
        }
      
    }

    public void setActivePortfolio(positions posin) {
        actPositions = posin;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        runTraderRadioButton = new javax.swing.JRadioButton();
        goButton = new javax.swing.JButton();
        tickerComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        doneButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Set Run Position Filename ");
        setName("");

        jPanel1.setName("Set Run Position Filename");

        runTraderRadioButton.setText("Run Trader");
        runTraderRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runTraderRadioButtonActionPerformed(evt);
            }
        });

        goButton.setText("Go");
        goButton.setActionCommand("");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        tickerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tickerComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Select Position");

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(109, 109, 109)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(tickerComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jLabel3))
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(doneButton)
                                .add(runTraderRadioButton))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(123, 123, 123)
                        .add(goButton)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tickerComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(35, 35, 35)
                .add(runTraderRadioButton)
                .add(38, 38, 38)
                .add(goButton)
                .add(27, 27, 27)
                .add(doneButton)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runTraderRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runTraderRadioButtonActionPerformed
        
        if (runTraderRadioButton.isSelected() == true) {
            runTrader = true;
            if (actPositions.getPositionFileName() != null) {
                readyToRun = true;
            }else {
                readyToRun = false;
            }
        }else{
            runTrader = false;
        }
    }//GEN-LAST:event_runTraderRadioButtonActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
       if (readyToRun == true) {
           System.out.println("reading position information from file.");
             actPositions.posDataReadFromDisk(actPositions.getPositionFileName()/*"tdsave1test.dat"*/, true /* prompt ? */);
             
             System.out.println("reading volitility monitor information from disk...");
             actPositions.getVmManager().readFromDisk(actPositions.getPositionFileName());
             
             // start stats
             actStats = new positionStatistics();
             System.out.println("reading statistics information from file.");
             actStats.statReadFromDisk(actPositions.getPositionFileName()/*"tdsave1test"*/, false /* no prompt */);
             actTrader = new positionTrader(actPositions, positionConfig.getActConfig());
             actTrader.setStatistic(actStats);
             System.out.println("starting up status screen.");
             if (actTrader != null) {
                 actTrader.runStatusScreen();

             } else {
                 commonGui.prMsg("Trader not currently running, so Cannot run Status.");
             }
             System.out.println("enabling chart logging.");
             if (actChart == null) {
                 actChart = new positionChart(actPositions);
                 actTrader.setChart(actChart);
             } else {
                 actTrader.setChart(actChart);
             }
             
             if(actTradeHandler == null ) {
                System.out.println("enabling tradeHandler.");
                actTradeHandler = new tradeHandler(actPositions);
                /* tradeHandler uses the file save of actTrader */
                actTradeHandler.setActTrader(actTrader);
             }
 //            System.out.println("reading volitility monitor information from disk...");
 //            dnPositions.getVmManager().readFromDisk(dnPositions.getPositionFileName());
             System.out.println("launching alarmsEvents...");
             actAlarmsEvents = new alarmsEvents(actPositions);
       }
    }//GEN-LAST:event_goButtonActionPerformed

    private void tickerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tickerComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tickerComboBoxActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_doneButtonActionPerformed

 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doneButton;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton runTraderRadioButton;
    private javax.swing.JComboBox tickerComboBox;
    // End of variables declaration//GEN-END:variables
}
